apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ap-south-1
  version: "1.30"

availabilityZones:
  - ap-south-1a
  - ap-south-1b

iam:
  withOIDC: true
  vpcResourceControllerPolicy: true

privateCluster:
  enabled: false
  skipEndpointCreation: false

# Remove managedNodeGroups section for initial creation
