apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${REGION}
  version: 1.30

availabilityZones:
  - ${AVAILABILITY_ZONES}

iam:
  withOIDC: true
  vpcResourceControllerPolicy: true

kubernetesNetworkConfig:
  serviceIPv4CIDR: ${SERVICE_CIDR}

privateCluster:
  enabled: false
  skipEndpointCreation: false

managedNodeGroups:
  - name: ${NODEGROUP_NAME}
    amiFamily: Ubuntu2204
    instanceTypes:
      - t3.small
      - t3a.small
      - t3a.medium
      - t3.medium
    desiredCapacity: ${NODE_COUNT}
    minSize: ${NODE_COUNT}
    maxSize: ${NODE_MAX_SIZE}
    spot: true
    privateNetworking: false
    ssh:
      allow: true
      publicKeyName: ${SSH_PUBLIC_KEY}
    tags:
      alpha.eksctl.io/nodegroup-name: ${NODEGROUP_NAME}
      alpha.eksctl.io/nodegroup-type: managed
    iam:
      withAddonPolicies:
        albIngress: true
        awsLoadBalancerController: true
        cloudWatch: true
    volumeType: gp3
    volumeSize: 80
    volumeIOPS: 3000
    volumeThroughput: 125
