apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${REGION}
  version: "1.30"

availabilityZones:
  - ${AVAILABILITY_ZONES}

iam:
  withOIDC: true
  vpcResourceControllerPolicy: true

kubernetesNetworkConfig:
  serviceIPv4CIDR: ${SERVICE_CIDR}

privateCluster:
  enabled: false
  skipEndpointCreation: false

# Remove managedNodeGroups section for initial creation
